Web/AccountingProject.Web/Controllers/CounterpartiesController.cs
namespace AccountingProject.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using AccountingProject.Common;
    using AccountingProject.Services.Data;
    using AccountingProject.Web.ViewModels.Counterparties;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.AllAccountantsRoleNames)]
    public class CounterpartiesController : Controller
    {
        private readonly ICounterpartiesService counterpartiesService;

        public CounterpartiesController(ICounterpartiesService counterpartiesService)
        {
            this.counterpartiesService = counterpartiesService;
        }

        // Counterparties/Create
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateCounterpartyInputModel input)
        {
            if (!await this.counterpartiesService.IsNameAvailableAsync(input.Name))
            {
                this.ModelState.AddModelError(nameof(input.Name), GlobalConstants.ErrorMessageForExistingName);
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.counterpartiesService.CreateAsync(input);
            this.TempData["Message"] = $"Counterparty \"{input.Name}\" has been added successfully.";
            return this.RedirectToAction(nameof(this.All));
        }

        // Counterparties/Edit
        public async Task<IActionResult> EditAsync(int id)
        {
            var viewModel = await this.counterpartiesService
                .GetByIdAsync<EditCounterpartyInputModel>(id);
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(
        [Bind("Name, VAT, Address, CityName")]
        int id, EditCounterpartyInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.counterpartiesService.UpdateAsync(id, input);
            this.TempData["Message"] = $"Counterparty \"{input.Name}\" has been edited successfully.";
            return this.RedirectToAction(nameof(this.All));
        }

        // Counterparties/Delete
        [HttpPost]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            await this.counterpartiesService.DeleteAsync(id);
            this.TempData["Message"] = $"Counterparty has been deleted successfully.";
            return this.RedirectToAction(nameof(this.All));
        }

        // Counterparties/All
        public IActionResult All()
        {
            var viewModel = new CounterpartiesListViewModel
            {
                Counterparties = this.counterpartiesService
                    .GetAll<CounterpartyViewModel>()
                    .OrderBy(x => x.Name),
            };
            return this.View(viewModel);
        }
    }
}

Web/AccountingProject.Web/Views/Counterparties/All.cshtml
@model AccountingProject.Web.ViewModels.Counterparties.CounterpartiesListViewModel
@{ this.ViewData["Title"] = "All Counterparties:"; }

@if (this.TempData.ContainsKey("Message"))
{
<div class="alert alert-success alert-dismissible fade show" role="alert">
    @this.TempData["Message"]
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>}

<h2 class="mx-auto w-50 text-center">@this.ViewData["Title"]</h2>

<div class="col-md-12 tex">
    <div class="page-header text-justify">
        <table class="table table-hover table-sm">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">VAT</th>
                    <th scope="col">Address</th>
                    <th scope="col">City</th>
                    <th class="text-center" scope="col">Edit</th>
                    <th class="text-center" scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var counterparty in this.Model.Counterparties)
                {
    <tr class="table-light">
        <th scope="row">@counterparty.Name</th>
        <td>@counterparty.VAT</td>
        <td>@counterparty.Address</td>
        <td>@counterparty.CityName</td>
        <td>
            <a class="btn btn-block btn-outline-warning" asp-controller="Counterparties" asp-action="Edit" asp-route-id="@counterparty.Id">Edit</a>
        </td>
        <td class="text-center">
            <form method="post" id="deleteForm_@counterparty.Id" asp-controller="Counterparties" asp-action="Delete" asp-route-id="@counterparty.Id">
            </form>
            <button class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteModal_@counterparty.Id">Delete</button>
            <div class="modal" id="deleteModal_@counterparty.Id">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Delete counterparty</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Do you really want to delete counterparty "@counterparty.Name"?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" onclick="(deleteForm_@counterparty.Id).submit()">Yes</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                        </div>
                    </div>
                </div>
            </div>
        </td>
    </tr>
}
            </tbody>
        </table>
    </div>
</div>

Web/AccountingProject.Web/Views/Counterparties/Create.cshtml
@model AccountingProject.Web.ViewModels.Counterparties.CreateCounterpartyInputModel
@{
    this.ViewData["Title"] = "Create a Counterparty";
}

<h1 class="mx-auto w-50">@this.ViewData["Title"]</h1>

<form class="mx-auto w-50" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="VAT"></label>
        <input asp-for="VAT" class="form-control" />
        <span asp-validation-for="VAT" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CityName"></label>
        <input asp-for="CityName" class="form-control" />
        <span asp-validation-for="CityName" class="text-danger"></span>
    </div>
    <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-block btn-primary text-white mb-3">Create</button>
    </div>
</form>

Web/AccountingProject.Web/Views/Counterparties/Edit.cshtml
@model AccountingProject.Web.ViewModels.Counterparties.EditCounterpartyInputModel
@{
    this.ViewData["Title"] = "Edit a Counterparty";
}

<h1 class="mx-auto w-50">@this.ViewData["Title"]</h1>

<form class="mx-auto w-50" method="post" id="editForm">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="VAT"></label>
        <input asp-for="VAT" class="form-control" />
        <span asp-validation-for="VAT" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CityName"></label>
        <input asp-for="CityName" class="form-control" />
        <span asp-validation-for="CityName" class="text-danger"></span>
    </div>
    <hr />
    <input type="hidden" asp-for="Id" />
    <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-block btn-primary text-white mb-3">Save changes</button>
    </div>
</form>