Web/AccountingProject.Web/Controllers/AnalyticalAccountsController.cs
namespace AccountingProject.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using AccountingProject.Common;
    using AccountingProject.Services.Data;
    using AccountingProject.Web.ViewModels.AnalyticalAccounts;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.AllAccountantsRoleNames)]
    public class AnalyticalAccountsController : Controller
    {
        private readonly IAnalyticalAccountsService analyticalAccountsService;
        private readonly IMainAccountsService mainAccountsService;

        public AnalyticalAccountsController(IAnalyticalAccountsService analyticalAccountsService, IMainAccountsService mainAccountsService)
        {
            this.analyticalAccountsService = analyticalAccountsService;
            this.mainAccountsService = mainAccountsService;
        }

        // AnalyticalAccounts/Create
        [Authorize(Roles = GlobalConstants.ChiefAccountantRoleName)]
        public IActionResult Create()
        {
            var viewModel = new CreateAnalyticalAccountInputModel { };
            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.ChiefAccountantRoleName)]
        public async Task<IActionResult> Create([Bind("Name,MainAccountId")]
        CreateAnalyticalAccountInputModel input)
        {
            if (!await this.analyticalAccountsService.IsNameAvailableAsync(input.Name, input.MainAccountId))
            {
                this.ModelState.AddModelError(nameof(input.Name), GlobalConstants.ErrorMessageForExistingName);
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.analyticalAccountsService.CreateAsync(input);
            this.TempData["Message"] = $"Analytical account \"{input.Name}\" has been added successfully.";
            return this.RedirectToAction(nameof(this.All));
        }

        // AnalyticalAccounts/Edit
        [Authorize(Roles = GlobalConstants.ChiefAccountantRoleName)]
        public async Task<IActionResult> EditAsync(int id)
        {
            var viewModel = await this.analyticalAccountsService
                .GetByIdAsync<EditAnalyticalAccountInputModel>(id);
            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.ChiefAccountantRoleName)]
        public async Task<IActionResult> Edit(
        [Bind("Name")]
        int id, EditAnalyticalAccountInputModel input)
        {
            if (!await this.analyticalAccountsService.IsNameAvailableAsync(input.Name, input.MainAccountId))
            {
                this.ModelState.AddModelError(nameof(input.Name), GlobalConstants.ErrorMessageForExistingName);
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.analyticalAccountsService.UpdateAsync(id, input);
            this.TempData["Message"] = $"Analytical account \"{input.Name}\" has been edited successfully.";
            return this.RedirectToAction(nameof(this.All));
        }

        // AnalyticalAccounts/Delete
        [HttpPost]
        [Authorize(Roles = GlobalConstants.ChiefAccountantRoleName)]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var accountToDelete = await this.analyticalAccountsService
                .GetByIdAsync<AnalyticalAccountPartViewModel>(id);
            await this.analyticalAccountsService.DeleteAsync(id);
            this.TempData["Message"] = $"Account \"{accountToDelete.Name}\" has been deleted successfully.";
            return this.RedirectToAction(nameof(this.All));
        }

        // AnalyticalAccounts/All
        public IActionResult All()
        {
            var viewModel = new AnalyticalAccountsListViewModel
            {
                AnalyticalAccounts = this.analyticalAccountsService
                    .GetAll<AnalyticalAccountViewModel>()
                    .OrderBy(x => x.GLAccountCode)
                    .ThenBy(x => x.Name),
            };
            return this.View(viewModel);
        }
    }
}

Web/AccountingProject.Web/ViewComponents/ListMainAccountsViewComponent.cs
namespace AccountingProject.Web.ViewComponents
{
    using System.Collections.Generic;
    using System.Linq;

    using AccountingProject.Services.Data;
    using AccountingProject.Web.ViewModels.GLAccounts;
    using AccountingProject.Web.ViewModels.ViewComponents;
    using Microsoft.AspNetCore.Mvc;

    public class ListMainAccountsViewComponent : ViewComponent
    {
        private readonly IMainAccountsService mainAccountsService;

        public ListMainAccountsViewComponent(IMainAccountsService mainAccountsService)
        {
            this.mainAccountsService = mainAccountsService;
        }

        public IViewComponentResult Invoke(string typeOfAccount, int mainAccountId)
        {
            if (typeOfAccount == "all")
            {
                var viewModel = new ListOfMainAccountsViewModel
                {
                    MainAccountId = mainAccountId,
                    MainAccounts = this.mainAccountsService
                            .GetAllAsKeyValuePairs(),
                };
                return this.View(viewModel);
            }
            else if (typeOfAccount == "inventory")
            {
                var viewModel = new ListOfMainAccountsViewModel
                {
                    MainAccountId = mainAccountId,
                    MainAccounts = this.mainAccountsService
                            .GetInventoryAccounts<MainAccountPartViewModel>()
                            .Select(x => new KeyValuePair<string, string>(x.Id.ToString(), $"{x.Code} {x.Name}")),
                };
                return this.View(viewModel);
            }
            else if (typeOfAccount == "fixedAsset")
            {
                var viewModel = new ListOfMainAccountsViewModel
                {
                    MainAccountId = mainAccountId,
                    MainAccounts = this.mainAccountsService
                            .GetFixedAssetAccounts<MainAccountPartViewModel>()
                            .Select(x => new KeyValuePair<string, string>(x.Id.ToString(), $"{x.Code} {x.Name}")),
                };
                return this.View(viewModel);
            }

            return this.View();
        }
    }
}

Web/AccountingProject.Web/Views/AnalyticalAccounts/All.cshtml
@using AccountingProject.Common
@model AccountingProject.Web.ViewModels.AnalyticalAccounts.AnalyticalAccountsListViewModel
@{ this.ViewData["Title"] = "All Analytical Accounts:"; }

@if (this.TempData.ContainsKey("Message"))
{
<div class="alert alert-success alert-dismissible fade show" role="alert">
    @this.TempData["Message"]
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>}

<h2 class="mx-auto w-50 text-center">@this.ViewData["Title"]</h2>

<div class="col-md-12">
    <div class="page-header text-justify">
        <table class="table table-hover table-striped table-sm table-responsive">
            <thead>
                <tr>
                    <th scope="col">Main Account Code</th>
                    <th scope="col">Main Account Name</th>
                    <th scope="col">Analytical Account Name</th>
                    <th scope="col">Debit Balance</th>
                    <th scope="col">Credit Balance</th>
                    @if (this.User.IsInRole(GlobalConstants.ChiefAccountantRoleName))
                    {
        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>            }
                </tr>
            </thead>
            <tbody>
                @foreach (var account in this.Model.AnalyticalAccounts)
                {
    <tr class="table-light">
        <th scope="row">@account.GLAccountCode</th>
        <td>@account.GLAccountName</td>
        <td>@account.Name</td>
        <td>@account.DebitBalance</td>
        <td>@account.CreditBalance</td>
        <td>
            @if (this.User.IsInRole(GlobalConstants.ChiefAccountantRoleName))
            {
<a class="btn btn-block btn-outline-warning" asp-controller="AnalyticalAccounts" asp-action="Edit" asp-route-id="@account.Id">Edit</a>}
        </td>
        <td>
            <form method="post" id="deleteForm_@account.Id" asp-controller="AnalyticalAccounts" asp-action="Delete" asp-route-id="@account.Id">
            </form>
            @if (this.User.IsInRole(GlobalConstants.ChiefAccountantRoleName))
            {
<button class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteModal_@account.Id">Delete</button>}
            <div class="modal" id="deleteModal_@account.Id">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Delete analytical account</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Do you really want to delete analytical account "@account.Name"?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" onclick="(deleteForm_@account.Id).submit()">Yes</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                        </div>
                    </div>
                </div>
            </div>
        </td>
    </tr>}
            </tbody>
        </table>
    </div>
</div>

Web/AccountingProject.Web/Views/AnalyticalAccounts/Create.cshtml
@model AccountingProject.Web.ViewModels.AnalyticalAccounts.CreateAnalyticalAccountInputModel
@{
    this.ViewData["Title"] = "Create an Analytical Account";    
}

<h1 class="mx-auto w-50">@this.ViewData["Title"]</h1>

<form class="mx-auto w-50" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <vc:list-main-accounts main-account-id="@Model.MainAccountId" type-of-account="all"></vc:list-main-accounts>
    
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-block btn-primary text-white mb-3">Create</button>
    </div>
</form>

Web/AccountingProject.Web/Views/AnalyticalAccounts/Edit.cshtml
@model AccountingProject.Web.ViewModels.AnalyticalAccounts.EditAnalyticalAccountInputModel
@{
    this.ViewData["Title"] = "Edit an Analytical Account";
}

<h1 class="mx-auto w-50">@this.ViewData["Title"]</h1>

<form class="mx-auto w-50" method="post" id="editForm">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="MainAccount"></label>
        <input asp-for="MainAccount" class="form-control" readonly/>        
        <span asp-validation-for="MainAccount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>    
    <hr />
    <input type="hidden" asp-for="Id" />
    <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-block btn-primary text-white mb-3">Save changes</button>
    </div>
</form>

@section Scripts {
    <script src="~/js/message_mainAccountCannotChange.js"></script>
}