Web/AccountingProject.Web/Controllers/DocumentTypesController.cs
namespace AccountingProject.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using AccountingProject.Common;
    using AccountingProject.Services.Data;
    using AccountingProject.Web.ViewModels.DocumentTypes;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.AllAccountantsRoleNames)]
    public class DocumentTypesController : Controller
    {
        private readonly IDocumentTypesService documentTypesService;

        public DocumentTypesController(IDocumentTypesService documentTypesService)
        {
            this.documentTypesService = documentTypesService;
        }

        // DocumentTypes/Create
        [Authorize(Roles = GlobalConstants.ChiefAccountantRoleName)]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.ChiefAccountantRoleName)]
        public async Task<IActionResult> Create(CreateDocumentTypeInputModel input)
        {
            if (!await this.documentTypesService.IsNameAvailableAsync(input.Name))
            {
                this.ModelState.AddModelError(nameof(input.Name), GlobalConstants.ErrorMessageForExistingName);
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.documentTypesService.CreateAsync(input);
            this.TempData["Message"] = $"Document type \"{input.Name}\" has been added successfully.";
            return this.RedirectToAction(nameof(this.All));
        }

        // DocumentTypes/Edit
        [Authorize(Roles = GlobalConstants.ChiefAccountantRoleName)]
        public async Task<IActionResult> EditAsync(int id)
        {
            var viewModel = await this.documentTypesService
                .GetByIdAsync<EditDocumentTypeInputModel>(id);
            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.ChiefAccountantRoleName)]
        public async Task<IActionResult> Edit(
        [Bind("Name")]
        int id, EditDocumentTypeInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.documentTypesService.UpdateAsync(id, input);
            this.TempData["Message"] = $"Document type \"{input.Name}\" has been edited successfully.";
            return this.RedirectToAction(nameof(this.All));
        }

        // DocumentTypes/Delete
        [HttpPost]
        [Authorize(Roles = GlobalConstants.ChiefAccountantRoleName)]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var documentToDelete = await this.documentTypesService
                .GetByIdAsync<DocumentTypePartViewModel>(id);
            await this.documentTypesService.DeleteAsync(id);
            this.TempData["Message"] = $"Document type \"{documentToDelete.Name}\" has been deleted successfully.";
            return this.RedirectToAction(nameof(this.All));
        }

        // DocumentTypes/All
        public IActionResult All()
        {
            var viewModel = new DocumentTypesListViewModel
            {
                DocumentTypes = this.documentTypesService
                    .GetAll<DocumentTypeViewModel>()
                    .OrderBy(x => x.Name),
            };
            return this.View(viewModel);
        }
    }
}

Web/AccountingProject.Web/Controllers/FixedAssetsController.cs
namespace AccountingProject.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using AccountingProject.Common;
    using AccountingProject.Services.Data;
    using AccountingProject.Web.ViewModels.FixedAssets;
    using AccountingProject.Web.ViewModels.ViewComponents;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.AllAccountantsRoleNames)]
    public class FixedAssetsController : Controller
    {
        private readonly IMainAccountsService mainAccountsService;
        private readonly IFixedAssetsService fixedAssetsService;

        public FixedAssetsController(
            IMainAccountsService mainAccountsService,
            IFixedAssetsService fixedAssetsService)
        {
            this.mainAccountsService = mainAccountsService;
            this.fixedAssetsService = fixedAssetsService;
        }

        // FixedAssets/Create
        public IActionResult Create()
        {
            var viewModel = new CreateFixedAssetInputModel
            {
                AcquisitionDate = DateTime.UtcNow,
            };
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateFixedAssetInputModel input)
        {
            if (!await this.fixedAssetsService.IsNameAvailableAsync(input.Name))
            {
                this.ModelState.AddModelError(nameof(input.Name), GlobalConstants.ErrorMessageForExistingName);
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.fixedAssetsService.CreateAsync(input);
            this.TempData["Message"] = $"Fixed asset \"{input.Name}\" has been added successfully.";

            return this.RedirectToAction(nameof(this.All));
        }

        // FixedAssets/All
        public async Task<IActionResult> All()
        {
            var viewModel = new FixedAssetsListViewModel
            {
                FixedAssets = await this.fixedAssetsService
                    .GetAllAsync<FixedAssetInListViewModel>(),
            };
            return this.View(viewModel);
        }

        // FixedAssets/ById
        public async Task<IActionResult> ByIdAsync(int id)
        {
            var fixedAsset = await this.fixedAssetsService
                .GetByIdAsync<FixedAssetViewModel>(id);
            return this.View(fixedAsset);
        }

        // FixedAssets/Delete
        [HttpPost]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            await this.fixedAssetsService.DeleteAsync(id);
            this.TempData["Message"] = $"Fixed asset has been deleted successfully.";
            return this.RedirectToAction(nameof(this.All));
        }

        // FixedAssets/Edit
        public async Task<IActionResult> EditAsync(int id)
        {
            var viewModel = await this.fixedAssetsService
                .GetByIdAsync<EditFixedAssetInputModel>(id);
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(int id, EditFixedAssetInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.fixedAssetsService.UpdateAsync(id, input);
            this.TempData["Message"] = $"Fixed asset \"{input.Name}\" has been edited successfully.";
            return this.RedirectToAction(nameof(this.All));
        }

        // FixedAssets/ChooseAccount
        public IActionResult ChooseAccount()
        {
            var viewModel = new ListOfMainAccountsViewModel { };
            viewModel.TypeOfAccount = "fixedAsset";
            return this.View("~/Views/Shared/ChooseAccount.cshtml", viewModel);
        }

        [HttpPost]
        public IActionResult ChooseAccount(ListOfMainAccountsViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View("~/Views/Shared/ChooseAccount.cshtml", input);
            }

            return this.RedirectToAction(nameof(this.AllByAccount), new { mainAccountId = input.MainAccountId });
        }

        // FixedAssets/AllByAccount
        public IActionResult AllByAccount(int mainAccountId)
        {
            var viewModel = new FixedAssetsListViewModel
            {
                FixedAssets = this.fixedAssetsService
                    .GetAllByAccount<FixedAssetInListViewModel>(mainAccountId),
            };
            return this.View(nameof(this.All), viewModel);
        }
    }
}

Web/AccountingProject.Web/Controllers/InventoriesController.cs
namespace AccountingProject.Web.Controllers
{
    using System.Threading.Tasks;

    using AccountingProject.Common;
    using AccountingProject.Services.Data;
    using AccountingProject.Web.ViewModels.Inventories;
    using AccountingProject.Web.ViewModels.ViewComponents;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.AllAccountantsRoleNames)]
    public class InventoriesController : Controller
    {
        private readonly IMainAccountsService mainAccountsService;
        private readonly IInventoriesService inventoriesService;

        public InventoriesController(IMainAccountsService mainAccountsService, IInventoriesService inventoriesService)
        {
            this.mainAccountsService = mainAccountsService;
            this.inventoriesService = inventoriesService;
        }

        // Inventories/Create
        public IActionResult Create()
        {
            var viewModel = new CreateInventoryInputModel { };
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,Measure," +
            "Quantity,Price,MainAccountId")]
            CreateInventoryInputModel input)
        {
            if (!await this.inventoriesService.IsNameAvailableAsync(input.Name))
            {
                this.ModelState.AddModelError(nameof(input.Name), GlobalConstants.ErrorMessageForExistingName);
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.inventoriesService.CreateAsync(input);
            this.TempData["Message"] = $"Inventory \"{input.Name}\" has been added successfully.";
            return this.RedirectToAction(nameof(this.All));
        }

        // Inventories/Edit
        public async Task<IActionResult> EditAsync(int id)
        {
            var viewModel = await this.inventoriesService
                .GetByIdAsync<EditInventoryInputModel>(id);
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(
        [Bind("Name, Measure, Quantity, Price, MainAccountId")]
        int id, EditInventoryInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.inventoriesService.UpdateAsync(id, input);
            this.TempData["Message"] = $"Inventory \"{input.Name}\" has been edited successfully.";
            return this.RedirectToAction(nameof(this.All));
        }

        // Inventories/Delete
        [HttpPost]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var inventoryToDelete = await this.inventoriesService
                .GetByIdAsync<InventoryViewModel>(id);
            await this.inventoriesService.DeleteAsync(id);
            this.TempData["Message"] = $"Inventory \"{inventoryToDelete.Name}\" has been deleted successfully.";
            return this.RedirectToAction(nameof(this.All));
        }

        // Inventories/All
        public IActionResult All()
        {
            var viewModel = new InventoriesListViewModel
            {
                Inventories = this.inventoriesService
                    .GetAll<InventoryViewModel>(),
            };
            return this.View(viewModel);
        }

        // Inventories/ChooseAccount
        public IActionResult ChooseAccount()
        {
            var viewModel = new ListOfMainAccountsViewModel { };
            viewModel.TypeOfAccount = "inventory";
            return this.View("~/Views/Shared/ChooseAccount.cshtml", viewModel);
        }

        [HttpPost]
        public IActionResult ChooseAccount(ListOfMainAccountsViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View("~/Views/Shared/ChooseAccount.cshtml", input);
            }

            return this.RedirectToAction(nameof(this.AllByAccount), new { mainAccountId = input.MainAccountId });
        }

        // Inventories/AllByAccount
        public IActionResult AllByAccount(int mainAccountId)
        {
            var viewModel = new InventoriesListViewModel
            {
                Inventories = this.inventoriesService
                    .GetAllByAccount<InventoryViewModel>(mainAccountId),
            };
            return this.View(nameof(this.All), viewModel);
        }
    }
}

Web/AccountingProject.Web/Controllers/SettingsController.cs
namespace AccountingProject.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using AccountingProject.Data.Common.Repositories;
    using AccountingProject.Data.Models;
    using AccountingProject.Services.Data;
    using AccountingProject.Web.ViewModels.Settings;

    using Microsoft.AspNetCore.Mvc;

    public class SettingsController : BaseController
    {
        private readonly ISettingsService settingsService;

        private readonly IDeletableEntityRepository<Setting> repository;

        public SettingsController(ISettingsService settingsService, IDeletableEntityRepository<Setting> repository)
        {
            this.settingsService = settingsService;
            this.repository = repository;
        }

        public IActionResult Index()
        {
            var settings = this.settingsService.GetAll<SettingViewModel>();
            var model = new SettingsListViewModel { Settings = settings };
            return this.View(model);
        }

        public async Task<IActionResult> InsertSetting()
        {
            var random = new Random();
            var setting = new Setting { Name = $"Name_{random.Next()}", Value = $"Value_{random.Next()}" };

            await this.repository.AddAsync(setting);
            await this.repository.SaveChangesAsync();

            return this.RedirectToAction(nameof(this.Index));
        }
    }
}

Web/AccountingProject.Web/Views/Shared/ChooseAccount.cshtml
@model AccountingProject.Web.ViewModels.ViewComponents.ListOfMainAccountsViewModel
@{
    this.ViewData["Title"] = "Choose an account";
}

<h2 class="mx-auto w-50">@this.ViewData["Title"]</h2>

<form class="mx-auto w-50" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <cache expires-sliding="TimeSpan.FromSeconds(30)">
        <vc:list-main-accounts main-account-id="@Model.MainAccountId" type-of-account="@Model.TypeOfAccount"></vc:list-main-accounts>
    </cache>

    <div class="d-flex justify-content-center">        
        <button type="submit" class="btn btn-block btn-primary text-white mb-3"> View List</button>
    </div>
</form>

Web/AccountingProject.Web/Views/Shared/ChoosePeriod.cshtml
@model AccountingProject.Web.ViewModels.Shared.InputYearMonthModel
@{
    this.ViewData["Title"] = "Choose a period";    
}

<h1 class="mx-auto w-50">@this.ViewData["Title"]</h1>

<form class="mx-auto w-50" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Year"></label>
        <input asp-for="Year" class="form-control" />
        <span asp-validation-for="Year" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="MonthStart"></label>
        <input asp-for="MonthStart" class="form-control" />
        <span asp-validation-for="MonthStart" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="MonthEnd"></label>
        <input asp-for="MonthEnd" class="form-control" />
        <span asp-validation-for="MonthEnd" class="text-danger"></span>
    </div>    
    <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-block btn-primary text-white mb-3">Report</button>
    </div>
</form>

Web/AccountingProject.Web/Views/Shared/StatusCodeError403.cshtml
<link href="~/css/error403.css" rel="stylesheet" />
<div class="maincontainer">
    <div class="bat">
        <img class="wing leftwing"
             src="https://www.blissfullemon.com/wp-content/uploads/2018/09/bat-wing.png">
        <img class="body"
             src="https://www.blissfullemon.com/wp-content/uploads/2018/09/bat-body.png" alt="bat">
        <img class="wing rightwing"
             src="https://www.blissfullemon.com/wp-content/uploads/2018/09/bat-wing.png">
    </div>
    <div class="bat">
        <img class="wing leftwing"
             src="https://www.blissfullemon.com/wp-content/uploads/2018/09/bat-wing.png">
        <img class="body"
             src="https://www.blissfullemon.com/wp-content/uploads/2018/09/bat-body.png" alt="bat">
        <img class="wing rightwing"
             src="https://www.blissfullemon.com/wp-content/uploads/2018/09/bat-wing.png">
    </div>
    <div class="bat">
        <img class="wing leftwing"
             src="https://www.blissfullemon.com/wp-content/uploads/2018/09/bat-wing.png">
        <img class="body"
             src="https://www.blissfullemon.com/wp-content/uploads/2018/09/bat-body.png" alt="bat">
        <img class="wing rightwing"
             src="https://www.blissfullemon.com/wp-content/uploads/2018/09/bat-wing.png">
    </div>
    <img class="foregroundimg" src="https://www.blissfullemon.com/wp-content/uploads/2018/09/HauntedHouseForeground.png" alt="haunted house">

</div>
<h1 class="errorcode">ERROR 403</h1>
<div class="errortext">This area is forbidden. Turn back now!</div>

Web/AccountingProject.Web/Views/Shared/StatusCodeError404.cshtml
<link href="~/css/error404.css" rel="stylesheet" />
<section class="page_404">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 ">
                <div class="col-sm-10 col-sm-offset-1  text-center">
                    <div class="four_zero_four_bg">
                        <h1 class="text-center ">404</h1>
                    </div>
                    <div class="contant_box_404">
                        <h3 class="h2">
                            Look like you're lost
                        </h3>
                        <p>the page you are looking for not avaible!</p>
                        <a class="link_404" asp-area="" asp-controller="Home" asp-action="Index">Go to Home Page</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Web/AccountingProject.Web/Views/Shared/StatusCodeErrorRest.cshtml
@{
    this.ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

Web/AccountingProject.Web/Views/Shared/_Layout - original.cshtml
@using AccountingProject.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Settings" asp-action="Index">Settings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/AccountingProject.Web/Views/Shared/_Layout.cshtml
@using AccountingProject.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />        
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="#navbarColor01"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" id="navbarColor01">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Administration" asp-controller="Dashboard" asp-action="Index">All users</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Identity" asp-page="/Account/Register">Register new user</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Administration" asp-controller="Dashboard" asp-action="AddUserToRole">Add User To Role</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Create</a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-area="" asp-controller="Transactions" asp-action="Create">Transaction</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Counterparties" asp-action="Create">Counterparty</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Inventories" asp-action="Create">Inventory</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="FixedAssets" asp-action="Create">Fixed Asset</a>
                                        @if (this.User.IsInRole(GlobalConstants.ChiefAccountantRoleName))
                                        {
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" asp-area="" asp-controller="MainAccounts" asp-action="Create">Main Account</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="AnalyticalAccounts" asp-action="Create">Analytical Account</a>
                                            <a class="dropdown-item" asp-area="" asp-controller="DocumentTypes" asp-action="Create">Document Type</a>
                                        }
                                    </div>
                                </li>
                                @if (this.User.IsInRole(GlobalConstants.ChiefAccountantRoleName))
                                {
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Initial Set</a>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" asp-area="" asp-controller="MainAccounts" asp-action="SetBalance">Set Initial Balance</a>
                                        </div>
                                    </li>
                                }
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">View all</a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-area="" asp-controller="Transactions" asp-action="AllByDocumentDate">Transactions ordered by document date</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Counterparties" asp-action="All">Counterparties</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Inventories" asp-action="All">Inventories</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Inventories" asp-action="ChooseAccount">Inventories by account</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="FixedAssets" asp-action="All">Fixed Assets</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="FixedAssets" asp-action="ChooseAccount">Fixed Assets by account</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="MainAccounts" asp-action="All">Main Accounts</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="AnalyticalAccounts" asp-action="All">Analytical Accounts</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="DocumentTypes" asp-action="All">Document Types</a>
                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Reports</a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-area="" asp-controller="Transactions" asp-action="SearchTransaction">Search Transaction</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Transactions" asp-action="ChoosePeriod">Transactions for a period</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="MainAccounts" asp-action="ChoosePeriod">Trial Balance</a>
                                    </div>
                                </li>
                            }
                        }
                    </ul>                    
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>